name: publish

on:
  push:
    branches:
      - master
      - beta

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: UseNode
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.0

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install
          pnpm run release
